import { useState } from "react";
import { Routes, Route } from "react-router-dom";
import BloodBag from "./Components/BloodBottle";
import Home from "./Components/Home";
import Navbar from "./Components/Navbar";
import SearchDonors from "./Components/SearchDonors";
import Footer from "./Components/Footer";
import HowItWorks from "./Components/HowItWorks";
import HeroSection from "./Components/HeroSection";
import About from "./Components/About";
import ContactUs from "./Components/ContactUs";
import Registration from "./Components/Registration";

//* 50 Fake Donors details :
const fakeDonors1 = [
  {
    id: 1,
    name: "Ali Khan",
    age: 28,
    gender: "Male",
    bloodGroup: "A+",
    city: "Karachi",
    contact: "0300-1234567",
    email: "ali.khan@example.com",
  },
  {
    id: 2,
    name: "Sara Ahmed",
    age: 24,
    gender: "Female",
    bloodGroup: "B+",
    city: "Lahore",
    contact: "0312-9876543",
    email: "sara.ahmed@example.com",
  },
  {
    id: 3,
    name: "Hamza Malik",
    age: 30,
    gender: "Male",
    bloodGroup: "O-",
    city: "Islamabad",
    contact: "0333-1112233",
    email: "hamza.malik@example.com",
  },
  {
    id: 4,
    name: "Zainab Noor",
    age: 22,
    gender: "Female",
    bloodGroup: "AB+",
    city: "Faisalabad",
    contact: "0345-2223344",
    email: "zainab.noor@example.com",
  },
  {
    id: 5,
    name: "Usman Ali",
    age: 35,
    gender: "Male",
    bloodGroup: "B-",
    city: "Rawalpindi",
    contact: "0308-5556677",
    email: "usman.ali@example.com",
  },
  {
    id: 6,
    name: "Maryam Sheikh",
    age: 27,
    gender: "Female",
    bloodGroup: "A-",
    city: "Multan",
    contact: "0321-4445566",
    email: "maryam.sheikh@example.com",
  },
  {
    id: 7,
    name: "Bilal Hussain",
    age: 29,
    gender: "Male",
    bloodGroup: "O+",
    city: "Peshawar",
    contact: "0315-9998877",
    email: "bilal.hussain@example.com",
  },
  {
    id: 8,
    name: "Hina Rauf",
    age: 26,
    gender: "Female",
    bloodGroup: "A+",
    city: "Sialkot",
    contact: "0302-1112233",
    email: "hina.rauf@example.com",
  },
  {
    id: 9,
    name: "Fahad Iqbal",
    age: 31,
    gender: "Male",
    bloodGroup: "AB-",
    city: "Quetta",
    contact: "0348-7776655",
    email: "fahad.iqbal@example.com",
  },
  {
    id: 10,
    name: "Nida Yasir",
    age: 25,
    gender: "Female",
    bloodGroup: "O+",
    city: "Hyderabad",
    contact: "0331-1234321",
    email: "nida.yasir@example.com",
  },
  {
    id: 11,
    name: "Imran Siddiqui",
    age: 34,
    gender: "Male",
    bloodGroup: "B+",
    city: "Gujranwala",
    contact: "0311-2221122",
    email: "imran.siddiqui@example.com",
  },
  {
    id: 12,
    name: "Sana Fatima",
    age: 23,
    gender: "Female",
    bloodGroup: "A-",
    city: "Bahawalpur",
    contact: "0307-5557788",
    email: "sana.fatima@example.com",
  },
  {
    id: 13,
    name: "Adnan Sharif",
    age: 32,
    gender: "Male",
    bloodGroup: "O-",
    city: "Sargodha",
    contact: "0322-6668899",
    email: "adnan.sharif@example.com",
  },
  {
    id: 14,
    name: "Rabia Javed",
    age: 29,
    gender: "Female",
    bloodGroup: "B-",
    city: "Kasur",
    contact: "0317-4443322",
    email: "rabia.javed@example.com",
  },
  {
    id: 15,
    name: "Kashif Raza",
    age: 27,
    gender: "Male",
    bloodGroup: "A+",
    city: "Mardan",
    contact: "0301-1239876",
    email: "kashif.raza@example.com",
  },
  {
    id: 16,
    name: "Ayesha Khan",
    age: 21,
    gender: "Female",
    bloodGroup: "AB+",
    city: "Sukkur",
    contact: "0336-5553344",
    email: "ayesha.khan@example.com",
  },
  {
    id: 17,
    name: "Shahid Mehmood",
    age: 36,
    gender: "Male",
    bloodGroup: "B+",
    city: "Okara",
    contact: "0324-6661122",
    email: "shahid.mehmood@example.com",
  },
  {
    id: 18,
    name: "Iqra Anwar",
    age: 24,
    gender: "Female",
    bloodGroup: "O+",
    city: "Chiniot",
    contact: "0342-9998876",
    email: "iqra.anwar@example.com",
  },
  {
    id: 19,
    name: "Tahir Nawaz",
    age: 33,
    gender: "Male",
    bloodGroup: "A-",
    city: "Jhelum",
    contact: "0319-5557788",
    email: "tahir.nawaz@example.com",
  },
  {
    id: 20,
    name: "Mehwish Arif",
    age: 28,
    gender: "Female",
    bloodGroup: "B-",
    city: "Abbottabad",
    contact: "0306-1234455",
    email: "mehwish.arif@example.com",
  },

  {
    id: 21,
    name: "Asad Rauf",
    age: 40,
    gender: "Male",
    bloodGroup: "A-",
    city: "Larkana",
    contact: "0328-5566771",
    email: "asad.rauf@example.com",
  },
  {
    id: 22,
    name: "Zoya Malik",
    age: 26,
    gender: "Female",
    bloodGroup: "O-",
    city: "Gwadar",
    contact: "0344-2233119",
    email: "zoya.malik@example.com",
  },
  {
    id: 23,
    name: "Danish Ali",
    age: 28,
    gender: "Male",
    bloodGroup: "B-",
    city: "Skardu",
    contact: "0335-7766552",
    email: "danish.ali@example.com",
  },
  {
    id: 24,
    name: "Aiman Riaz",
    age: 24,
    gender: "Female",
    bloodGroup: "AB-",
    city: "Khairpur",
    contact: "0316-9988774",
    email: "aiman.riaz@example.com",
  },
  {
    id: 25,
    name: "Hassan Javed",
    age: 32,
    gender: "Male",
    bloodGroup: "A+",
    city: "Chiniot",
    contact: "0306-4455662",
    email: "hassan.javed@example.com",
  },
  {
    id: 26,
    name: "Sana Gul",
    age: 25,
    gender: "Female",
    bloodGroup: "O+",
    city: "Kotli",
    contact: "0347-8899001",
    email: "sana.gul@example.com",
  },
  {
    id: 27,
    name: "Rehan Saeed",
    age: 35,
    gender: "Male",
    bloodGroup: "B+",
    city: "Mingora",
    contact: "0313-2211445",
    email: "rehan.saeed@example.com",
  },
  {
    id: 28,
    name: "Amna Tariq",
    age: 27,
    gender: "Female",
    bloodGroup: "AB+",
    city: "Muzaffarabad",
    contact: "0302-6677881",
    email: "amna.tariq@example.com",
  },
  {
    id: 29,
    name: "Nouman Shah",
    age: 31,
    gender: "Male",
    bloodGroup: "A-",
    city: "Dera Ghazi Khan",
    contact: "0322-1122338",
    email: "nouman.shah@example.com",
  },
  {
    id: 30,
    name: "Hiba Akram",
    age: 23,
    gender: "Female",
    bloodGroup: "B-",
    city: "Kohat",
    contact: "0336-5544332",
    email: "hiba.akram@example.com",
  },
  {
    id: 31,
    name: "Fahad Zafar",
    age: 29,
    gender: "Male",
    bloodGroup: "O-",
    city: "Turbat",
    contact: "0311-2233447",
    email: "fahad.zafar@example.com",
  },
  {
    id: 32,
    name: "Mehak Junaid",
    age: 21,
    gender: "Female",
    bloodGroup: "AB-",
    city: "Hunza",
    contact: "0305-6677883",
    email: "mehak.junaid@example.com",
  },
  {
    id: 33,
    name: "Shahid Iqbal",
    age: 37,
    gender: "Male",
    bloodGroup: "A+",
    city: "Muridke",
    contact: "0348-4433226",
    email: "shahid.iqbal@example.com",
  },
  {
    id: 34,
    name: "Areeba Khalid",
    age: 28,
    gender: "Female",
    bloodGroup: "B+",
    city: "Khuzdar",
    contact: "0324-1122774",
    email: "areeba.khalid@example.com",
  },
  {
    id: 35,
    name: "Omer Siddiqui",
    age: 34,
    gender: "Male",
    bloodGroup: "O+",
    city: "Hafizabad",
    contact: "0317-9988775",
    email: "omer.siddiqui@example.com",
  },
  {
    id: 36,
    name: "Laiba Sheikh",
    age: 22,
    gender: "Female",
    bloodGroup: "AB+",
    city: "Kharian",
    contact: "0303-5566778",
    email: "laiba.sheikh@example.com",
  },
  {
    id: 37,
    name: "Rizwan Anis",
    age: 33,
    gender: "Male",
    bloodGroup: "A-",
    city: "Mianwali",
    contact: "0340-2233557",
    email: "rizwan.anis@example.com",
  },
  {
    id: 38,
    name: "Sadia Anwar",
    age: 25,
    gender: "Female",
    bloodGroup: "B-",
    city: "Vehari",
    contact: "0329-6677880",
    email: "sadia.anwar@example.com",
  },
  {
    id: 39,
    name: "Kashif Mehmood",
    age: 36,
    gender: "Male",
    bloodGroup: "O-",
    city: "Narowal",
    contact: "0300-4455776",
    email: "kashif.mehmood@example.com",
  },
  {
    id: 40,
    name: "Aleena Shahid",
    age: 24,
    gender: "Female",
    bloodGroup: "AB-",
    city: "Charsadda",
    contact: "0330-2233664",
    email: "aleena.shahid@example.com",
  },
  {
    id: 41,
    name: "Moiz Rehman",
    age: 30,
    gender: "Male",
    bloodGroup: "A+",
    city: "Kasur",
    contact: "0318-1122559",
    email: "moiz.rehman@example.com",
  },
  {
    id: 42,
    name: "Iqra Habib",
    age: 26,
    gender: "Female",
    bloodGroup: "O+",
    city: "Attock",
    contact: "0301-6677990",
    email: "iqra.habib@example.com",
  },
  {
    id: 43,
    name: "Farhan Saqib",
    age: 35,
    gender: "Male",
    bloodGroup: "B+",
    city: "Bhakkar",
    contact: "0343-5544228",
    email: "farhan.saqib@example.com",
  },
  {
    id: 44,
    name: "Hira Younis",
    age: 23,
    gender: "Female",
    bloodGroup: "AB+",
    city: "Jhang",
    contact: "0326-2211775",
    email: "hira.younis@example.com",
  },
  {
    id: 45,
    name: "Shujaat Ali",
    age: 32,
    gender: "Male",
    bloodGroup: "A-",
    city: "Swabi",
    contact: "0338-6677552",
    email: "shujaat.ali@example.com",
  },
  {
    id: 46,
    name: "Aqsa Naveed",
    age: 27,
    gender: "Female",
    bloodGroup: "B-",
    city: "Kohlu",
    contact: "0319-9988777",
    email: "aqsa.naveed@example.com",
  },
  {
    id: 47,
    name: "Shoaib Arif",
    age: 38,
    gender: "Male",
    bloodGroup: "O-",
    city: "Mansehra",
    contact: "0309-3344551",
    email: "shoaib.arif@example.com",
  },
  {
    id: 48,
    name: "Rabia Zaman",
    age: 25,
    gender: "Female",
    bloodGroup: "AB-",
    city: "Tando Adam",
    contact: "0349-1122779",
    email: "rabia.zaman@example.com",
  },
  {
    id: 49,
    name: "Adeel Hanif",
    age: 29,
    gender: "Male",
    bloodGroup: "A+",
    city: "Khushab",
    contact: "0327-2233554",
    email: "adeel.hanif@example.com",
  },
  {
    id: 50,
    name: "Sumbal Rafiq",
    age: 22,
    gender: "Female",
    bloodGroup: "O+",
    city: "Shikarpur",
    contact: "0312-6677888",
    email: "sumbal.rafiq@example.com",
  },
];

const fakeDonors2 = [
  {
    id: 1,
    name: "Ali Khan",
    age: 28,
    gender: "Male",
    city: "Karachi",
    bloodGroup: "A+",
    contact: "0300-1111111",
    email: "ali.khan1@example.com",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    name: "Sara Ahmed",
    age: 24,
    gender: "Female",
    city: "Lahore",
    bloodGroup: "B+",
    contact: "0301-2222222",
    email: "sara.ahmed@example.com",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 3,
    name: "Hassan Raza",
    age: 32,
    gender: "Male",
    city: "Islamabad",
    bloodGroup: "O-",
    contact: "0302-3333333",
    email: "hassan.raza@example.com",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 4,
    name: "Ayesha Malik",
    age: 26,
    gender: "Female",
    city: "Karachi",
    bloodGroup: "AB+",
    contact: "0303-4444444",
    email: "ayesha.malik@example.com",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: 5,
    name: "Usman Tariq",
    age: 30,
    gender: "Male",
    city: "Lahore",
    bloodGroup: "B-",
    contact: "0304-5555555",
    email: "usman.tariq@example.com",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 6,
    name: "Maria Ali",
    age: 27,
    gender: "Female",
    city: "Rawalpindi",
    bloodGroup: "A-",
    contact: "0305-6666666",
    email: "maria.ali@example.com",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: 7,
    name: "Bilal Hussain",
    age: 29,
    gender: "Male",
    city: "Faisalabad",
    bloodGroup: "O+",
    contact: "0306-7777777",
    email: "bilal.hussain@example.com",
    image: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 8,
    name: "Fatima Noor",
    age: 23,
    gender: "Female",
    city: "Multan",
    bloodGroup: "AB-",
    contact: "0307-8888888",
    email: "fatima.noor@example.com",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: 9,
    name: "Ahmed Sheikh",
    age: 34,
    gender: "Male",
    city: "Karachi",
    bloodGroup: "B+",
    contact: "0308-9999999",
    email: "ahmed.sheikh@example.com",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    id: 10,
    name: "Zara Qureshi",
    age: 25,
    gender: "Female",
    city: "Peshawar",
    bloodGroup: "O+",
    contact: "0309-1010101",
    email: "zara.qureshi@example.com",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    id: 11,
    name: "Imran Abbas",
    age: 31,
    gender: "Male",
    city: "Quetta",
    bloodGroup: "A-",
    contact: "0310-1112222",
    email: "imran.abbas@example.com",
    image: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    id: 12,
    name: "Nida Farooq",
    age: 27,
    gender: "Female",
    city: "Hyderabad",
    bloodGroup: "B+",
    contact: "0311-3334444",
    email: "nida.farooq@example.com",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: 13,
    name: "Danish Shah",
    age: 29,
    gender: "Male",
    city: "Sialkot",
    bloodGroup: "O+",
    contact: "0312-5556666",
    email: "danish.shah@example.com",
    image: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    id: 14,
    name: "Mehwish Javed",
    age: 22,
    gender: "Female",
    city: "Karachi",
    bloodGroup: "AB-",
    contact: "0313-7778888",
    email: "mehwish.javed@example.com",
    image: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    id: 15,
    name: "Hamza Siddiqui",
    age: 35,
    gender: "Male",
    city: "Lahore",
    bloodGroup: "A+",
    contact: "0314-9990000",
    email: "hamza.siddiqui@example.com",
    image: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    id: 16,
    name: "Sana Gul",
    age: 26,
    gender: "Female",
    city: "Islamabad",
    bloodGroup: "O-",
    contact: "0315-1234567",
    email: "sana.gul@example.com",
    image: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    id: 17,
    name: "Adnan Iqbal",
    age: 33,
    gender: "Male",
    city: "Karachi",
    bloodGroup: "B-",
    contact: "0316-2345678",
    email: "adnan.iqbal@example.com",
    image: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    id: 18,
    name: "Komal Zahra",
    age: 24,
    gender: "Female",
    city: "Multan",
    bloodGroup: "AB+",
    contact: "0317-3456789",
    email: "komal.zahra@example.com",
    image: "https://randomuser.me/api/portraits/women/18.jpg",
  },
  {
    id: 19,
    name: "Shahzad Ali",
    age: 28,
    gender: "Male",
    city: "Karachi",
    bloodGroup: "O+",
    contact: "0318-4567890",
    email: "shahzad.ali@example.com",
    image: "https://randomuser.me/api/portraits/men/19.jpg",
  },
  {
    id: 20,
    name: "Hira Saeed",
    age: 25,
    gender: "Female",
    city: "Lahore",
    bloodGroup: "A-",
    contact: "0319-5678901",
    email: "hira.saeed@example.com",
    image: "https://randomuser.me/api/portraits/women/20.jpg",
  },
  {
    id: 21,
    name: "Waqas Jamil",
    age: 29,
    gender: "Male",
    city: "Faisalabad",
    bloodGroup: "B+",
    contact: "0320-6789012",
    email: "waqas.jamil@example.com",
    image: "https://randomuser.me/api/portraits/men/21.jpg",
  },
  {
    id: 22,
    name: "Iqra Naveed",
    age: 27,
    gender: "Female",
    city: "Karachi",
    bloodGroup: "O-",
    contact: "0321-7890123",
    email: "iqra.naveed@example.com",
    image: "https://randomuser.me/api/portraits/women/22.jpg",
  },
  {
    id: 23,
    name: "Saad Latif",
    age: 32,
    gender: "Male",
    city: "Islamabad",
    bloodGroup: "A+",
    contact: "0322-8901234",
    email: "saad.latif@example.com",
    image: "https://randomuser.me/api/portraits/men/23.jpg",
  },
  {
    id: 24,
    name: "Maha Irfan",
    age: 23,
    gender: "Female",
    city: "Lahore",
    bloodGroup: "AB-",
    contact: "0323-9012345",
    email: "maha.irfan@example.com",
    image: "https://randomuser.me/api/portraits/women/24.jpg",
  },
  {
    id: 25,
    name: "Tahir Mehmood",
    age: 36,
    gender: "Male",
    city: "Quetta",
    bloodGroup: "O+",
    contact: "0324-1234567",
    email: "tahir.mehmood@example.com",
    image: "https://randomuser.me/api/portraits/men/25.jpg",
  },
  {
    id: 26,
    name: "Huma Shafiq",
    age: 28,
    gender: "Female",
    city: "Karachi",
    bloodGroup: "B-",
    contact: "0325-2345678",
    email: "huma.shafiq@example.com",
    image: "https://randomuser.me/api/portraits/women/26.jpg",
  },
  {
    id: 27,
    name: "Asad Rehman",
    age: 34,
    gender: "Male",
    city: "Rawalpindi",
    bloodGroup: "A-",
    contact: "0326-3456789",
    email: "asad.rehman@example.com",
    image: "https://randomuser.me/api/portraits/men/27.jpg",
  },
  {
    id: 28,
    name: "Sadia Khalid",
    age: 26,
    gender: "Female",
    city: "Multan",
    bloodGroup: "AB+",
    contact: "0327-4567890",
    email: "sadia.khalid@example.com",
    image: "https://randomuser.me/api/portraits/women/28.jpg",
  },
  {
    id: 29,
    name: "Kamran Yousaf",
    age: 30,
    gender: "Male",
    city: "Karachi",
    bloodGroup: "O+",
    contact: "0328-5678901",
    email: "kamran.yousaf@example.com",
    image: "https://randomuser.me/api/portraits/men/29.jpg",
  },
  {
    id: 30,
    name: "Rabia Tariq",
    age: 24,
    gender: "Female",
    city: "Lahore",
    bloodGroup: "A+",
    contact: "0329-6789012",
    email: "rabia.tariq@example.com",
    image: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    id: 31,
    name: "Noman Arshad",
    age: 29,
    gender: "Male",
    city: "Karachi",
    bloodGroup: "B+",
    contact: "0330-7890123",
    email: "noman.arshad@example.com",
    image: "https://randomuser.me/api/portraits/men/31.jpg",
  },
  {
    id: 32,
    name: "Minal Qadir",
    age: 25,
    gender: "Female",
    city: "Hyderabad",
    bloodGroup: "AB-",
    contact: "0331-8901234",
    email: "minal.qadir@example.com",
    image: "https://randomuser.me/api/portraits/women/32.jpg",
  },
  {
    id: 33,
    name: "Junaid Ashraf",
    age: 31,
    gender: "Male",
    city: "Faisalabad",
    bloodGroup: "O-",
    contact: "0332-9012345",
    email: "junaid.ashraf@example.com",
    image: "https://randomuser.me/api/portraits/men/33.jpg",
  },
  {
    id: 34,
    name: "Areeba Hassan",
    age: 22,
    gender: "Female",
    city: "Islamabad",
    bloodGroup: "A-",
    contact: "0333-1234567",
    email: "areeba.hassan@example.com",
    image: "https://randomuser.me/api/portraits/women/34.jpg",
  },
  {
    id: 35,
    name: "Fahad Nadeem",
    age: 35,
    gender: "Male",
    city: "Karachi",
    bloodGroup: "B-",
    contact: "0334-2345678",
    email: "fahad.nadeem@example.com",
    image: "https://randomuser.me/api/portraits/men/35.jpg",
  },
  {
    id: 36,
    name: "Kiran Aziz",
    age: 27,
    gender: "Female",
    city: "Multan",
    bloodGroup: "O+",
    contact: "0335-3456789",
    email: "kiran.aziz@example.com",
    image: "https://randomuser.me/api/portraits/women/36.jpg",
  },
  {
    id: 37,
    name: "Murtaza Anwar",
    age: 33,
    gender: "Male",
    city: "Sialkot",
    bloodGroup: "AB+",
    contact: "0336-4567890",
    email: "murtaza.anwar@example.com",
    image: "https://randomuser.me/api/portraits/men/37.jpg",
  },
  {
    id: 38,
    name: "Aqsa Nisar",
    age: 24,
    gender: "Female",
    city: "Quetta",
    bloodGroup: "A+",
    contact: "0337-5678901",
    email: "aqsa.nisar@example.com",
    image: "https://randomuser.me/api/portraits/women/38.jpg",
  },
  {
    id: 39,
    name: "Rehan Saeed",
    age: 28,
    gender: "Male",
    city: "Karachi",
    bloodGroup: "O-",
    contact: "0338-6789012",
    email: "rehan.saeed@example.com",
    image: "https://randomuser.me/api/portraits/men/39.jpg",
  },
  {
    id: 40,
    name: "Shazia Munir",
    age: 26,
    gender: "Female",
    city: "Peshawar",
    bloodGroup: "B+",
    contact: "0339-7890123",
    email: "shazia.munir@example.com",
    image: "https://randomuser.me/api/portraits/women/40.jpg",
  },
  {
    id: 41,
    name: "Haseeb Akhtar",
    age: 29,
    gender: "Male",
    city: "Karachi",
    bloodGroup: "AB-",
    contact: "0340-8901234",
    email: "haseeb.akhtar@example.com",
    image: "https://randomuser.me/api/portraits/men/41.jpg",
  },
  {
    id: 42,
    name: "Sumbul Irshad",
    age: 23,
    gender: "Female",
    city: "Lahore",
    bloodGroup: "O+",
    contact: "0341-9012345",
    email: "sumbul.irshad@example.com",
    image: "https://randomuser.me/api/portraits/women/42.jpg",
  },
  {
    id: 43,
    name: "Omer Khalid",
    age: 32,
    gender: "Male",
    city: "Islamabad",
    bloodGroup: "B-",
    contact: "0342-1234567",
    email: "omer.khalid@example.com",
    image: "https://randomuser.me/api/portraits/men/43.jpg",
  },
  {
    id: 44,
    name: "Farah Ijaz",
    age: 25,
    gender: "Female",
    city: "Hyderabad",
    bloodGroup: "A+",
    contact: "0343-2345678",
    email: "farah.ijaz@example.com",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
  },
  {
    id: 45,
    name: "Shafiq Anjum",
    age: 34,
    gender: "Male",
    city: "Karachi",
    bloodGroup: "O+",
    contact: "0344-3456789",
    email: "shafiq.anjum@example.com",
    image: "https://randomuser.me/api/portraits/men/45.jpg",
  },
  {
    id: 46,
    name: "Mahnoor Riaz",
    age: 22,
    gender: "Female",
    city: "Multan",
    bloodGroup: "B+",
    contact: "0345-4567890",
    email: "mahnoor.riaz@example.com",
    image: "https://randomuser.me/api/portraits/women/46.jpg",
  },
  {
    id: 47,
    name: "Irfan Malik",
    age: 30,
    gender: "Male",
    city: "Faisalabad",
    bloodGroup: "AB+",
    contact: "0346-5678901",
    email: "irfan.malik@example.com",
    image: "https://randomuser.me/api/portraits/men/47.jpg",
  },
  {
    id: 48,
    name: "Hafsa Waqar",
    age: 27,
    gender: "Female",
    city: "Karachi",
    bloodGroup: "A-",
    contact: "0347-6789012",
    email: "hafsa.waqar@example.com",
    image: "https://randomuser.me/api/portraits/women/48.jpg",
  },
  {
    id: 49,
    name: "Rashid Mehmood",
    age: 35,
    gender: "Male",
    city: "Lahore",
    bloodGroup: "O-",
    contact: "0348-7890123",
    email: "rashid.mehmood@example.com",
    image: "https://randomuser.me/api/portraits/men/49.jpg",
  },
  {
    id: 50,
    name: "Amna Junaid",
    age: 24,
    gender: "Female",
    city: "Islamabad",
    bloodGroup: "AB-",
    contact: "0349-8901234",
    email: "amna.junaid@example.com",
    image: "https://randomuser.me/api/portraits/women/50.jpg",
  },
];

function App() {
  const [donors, setDonors] = useState(fakeDonors2); //* must start as empty array
  const [users, setUsers] = useState([]); //* same for users

  return (
    <>
      <div className="min-h-screen min-w-screen bg-gradient-to-b from-red-950 via-red-800 to-red-600 text-slate-100">
        <Navbar />

        <Routes>
          <Route path="/" element={<Home get_donors_state={donors} />} />
          {/* <Route index element={<Home get_donors_state={donors} />} /> */}
          <Route path="/about" element={<About />} />
          <Route path="/contact" element={<ContactUs />} />
          <Route
            path="/:pageName"
            element={<Home get_donors_state={donors} />}
          />

          <Route
            path="/DonorRegister"
            element={
              <Registration
                donors={donors}
                setDonors={setDonors}
                users={users}
                setUsers={setUsers}
              />
            }
          />
        </Routes>
        <Footer />
      </div>
    </>
  );
}

export default App;
